.github/workflows/android-pr.yml, .github/workflows/release-kdocs.yml, .github/workflows/release.yml, android-annotation/build.gradle, beagle/build.gradle, beagle/src/test/kotlin/br/com/zup/beagle/android/components/LazyComponentTest.kt, build.gradle, fastlane/Fastfile, gradle/report/jacoco.gradle, gradle/wrapper/gradle-wrapper.properties, internal-processor/build.gradle, preview/build.gradle, processor-shared-code/build.gradle, processor/build.gradle, sample/build.gradle, test/build.gradle
Updates Android Gradle Plugin to version 7.0.0
=> refactor: Update AGP

.github/workflows/horusec-pr.yml, horusec-config.json
Signed-off-by: Matheus Ribeiro <matheus.ribeiro@zup.com.br>
This PR uses the recommended installation configuration from horusec docs and fixes the validations.
=> fix: horusec validation

beagle/build.gradle, fastlane/Fastfile
Signed-off-by: Paulo Cesar Meurer <paulo.meurer@zup.com.br>
Configured lint according to some performance tips:
https://groups.google.com/g/lint-dev/c/RGTvK_uHQGQ/m/FjJA12aGBAAJ?pli=1
=> chore: refactor lint

beagle/src/main/kotlin/br/com/zup/beagle/android/action/AddChildren.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/Bind.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/data/serializer/adapter/BindAdapterFactory.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/action/AddChildrenTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/data/serializer/actions/SendRequestSerializerTest.kt
https://github.com/ZupIT/beagle/issues/1545
When the developer tries to Bind some list, for example: `Bind<List<ServerDrivenComponent>>` or  `Bind<List<User>>` in the beagle it doesn't evaluate to correct type, after debugging I saw the class BindAdapter one line removed the inheritance and I remove this part because the Moshi need to know this.
=> fix: adjust serialization to Bind of List<T>

beagle/src/main/kotlin/br/com/zup/beagle/analytics/Analytics.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/Bind.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/ServerDrivenFactory.kt
=> fix: add deprecated  in analytics and newServerDrivenIntent

beagle/src/main/kotlin/br/com/zup/beagle/android/components/layout/Screen.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/ToolbarManager.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/utils/ToolbarManagerTest.kt
Signed-off-by: Matheus Ribeiro <matheus.ribeiro@zup.com.br>
Part of [#1743](https://github.com/ZupIT/beagle/issues/1743)
This PR updates the `NavigationBarItem` contract inside the `Screen` component.
=> feat: NavigationBarItem contract refactored

.github/workflows/android-pr.yml
adjust env to workflow works after merge in main
=> chore: adjust env to workflow works after merge in main

CODEOWNERS
Signed-off-by: uziasferreirazup <uzias.ferreira@zup.com.br>
=> chore: update code owner

beagle/src/main/kotlin/br/com/zup/beagle/android/action/Navigate.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextData.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextDataManager.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextDataManipulator.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/ServerDrivenFactory.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/BeagleActivity.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/BeagleFragment.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/custom/BeagleNavigator.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/action/NavigateTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/utils/ServerDrivenFactoryKtTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/utils/ServerDrivenFactoryTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/BeagleActivityTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/BeagleFragmentTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/BeagleNavigatorTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModelTest.kt
https://github.com/ZupIT/beagle/issues/1740
adjust navigation context to the new contract
=> feat: adjust navigation context to the new contract

CONTRIBUTING.md, README.md
Signed-off-by: jessica-tw <jessica.olinda@zup.com.br>
- Fixed readme
- Added new contributing guide.
=> fix:  Readme and added Contributing Guide

.github/dependabot.yml
=> feat: Updates dependabot schedule

.github/workflows/android-pr.yml, .github/workflows/danger-pr.yml, .github/workflows/horusec-pr.yml, fastlane/Fastfile
=> feat: Removes unused secrets from workflows

.github/dependabot.yml, .github/workflows/horusec-pr.yml
- Updated horusec version to latest.
=> chore: Updates horusec version

.github/workflows/license-pr.yml
Updates header license checker action version
=> fix: Updates license header checker action

.github/workflows/android-pr.yml, .github/workflows/danger-pr.yml, CONTRIBUTING.md, README.md
Signed-off-by: Henrique Rodrigues <henrique.rodrigues@zup.com.br>
- remove the DCO information of the README.md
- Add the Issue section in the CONTRIBUTING.md
Related task: https://app.shortcut.com/devrelopensource/story/227756/atualizar-p%C3%A1gina-de-contributing
=> docs:update readme and contributing

beagle/src/main/kotlin/br/com/zup/beagle/android/components/list/ListAdapter.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/components/list/ListViewHolder.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/data/ComponentRequester.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/data/serializer/BeagleJsonSerializer.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/data/serializer/BeagleJsonSerializerFactory.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/data/serializer/BeagleSerializer.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/ViewGroupExtensions.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/BeagleActivity.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/BeagleFragment.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/data/serializer/BeagleJsonSerializerFactoryTest.kt
Adds BeagleJsonSerializerFactory to allow the users to create custom type adapters that need to know how to serialize/deserialize beagle components
Fixes https://github.com/ZupIT/beagle/issues/1799
Now the user can call the BeagleJsonSerializationFactory to delegate the responsability to serialize/deserialize beagle components
Example:
```
private const val KEY_NAME = "name"
interface Person {
val name: Text // This attribute should be serialized/deserialized by the Beagle platform
}
data class PersonImpl(override val name: Text) : Person
@RegisterBeagleAdapter
class PersonAdapter(private val serializer: BeagleJsonSerializer = BeagleJsonSerializerFactory.serializer) :
BeagleTypeAdapter<Person> {
override fun fromJson(json: String): Person {
val rootObject = JSONObject(json)
val …
```
=> feat: Adds BeagleJsonSerializerFactory

.github/workflows/horusec-pr.yml
Added horusec token for web manager
=> feat: Adds horusec web token

SECURITY.md
Updates security file with new e-mail
=> feat: Updates security file

beagle/src/main/kotlin/br/com/zup/beagle/android/view/BeagleFragment.kt, sample/src/main/kotlin/br/com/zup/beagle/sample/widgets/ActionExecutor.kt
Closes https://github.com/ZupIT/beagle/issues/1809
=> feat: Fixes double evaluation for navigation context

beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextActionExecutor.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ImplicitContextManager.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/BindExtensions.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ContextActionExecutorTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ImplicitContextManagerTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/utils/ActionExtensionsKtTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModelTest.kt
Signed-off-by: Hernand Azevedo <hernand.azevedo@zup.com.br>
Closes https://github.com/ZupIT/beagle/issues/1814
=> feat: Fixing implicit context for multi level evaluation

beagle/src/main/kotlin/br/com/zup/beagle/android/action/Navigate.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/utils/NavigationContextExtensions.kt
=> fix: Fixes evaluation of NavigationContext value if has an expression.

beagle/src/main/kotlin/br/com/zup/beagle/android/components/refresh/PullToRefresh.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/components/refresh/PullToRefreshTest.kt
Fixes resize of PullToRefresh childs components(in this case the ListView that was not resizing)
Fixes https://github.com/ZupIT/beagle/issues/1818
=> feat: Fixes Listview resizing when inside a PullToRefresh

beagle/src/main/kotlin/br/com/zup/beagle/android/components/GridView.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/components/ListView.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/components/list/ListAdapter.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/components/list/ListViewHolder.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextActionExecutor.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/ContextDataManager.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/context/GlobalContext.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModel.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/components/ListViewTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/components/list/ListAdapterTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/components/list/ListViewHolderTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ContextDataManagerTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/data/serializer/serializerDataFactory.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/view/viewmodel/ScreenContextViewModelTest.kt
https://github.com/ZupIT/beagle/issues/1819
- Expose list index value by implicit context with customizable via _indexName_ property in `ListView`/`GridView` model.
- Now setting the _item_ context will also set the original datasource in `ListView`/`GridView`.
=> feat: ListView datasource update + index 

beagle/src/main/kotlin/br/com/zup/beagle/android/operation/OperationType.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/OperationTypeExtensions.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/CombineOperationUtil.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/ComparisonValidationParameterOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/EqOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/GtOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/GteOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/LtOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/LteOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/convert/DoubleOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/convert/IntOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/convert/StringOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/number/DivideOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/number/MultiplyOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/number/SubtractOperation.kt, beagle/src/main/kotlin/br/com/zup/beagle/android/operation/builtin/number/SumOperation.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/EqOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/GtOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/GteOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/LtOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/comparison/LteOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/convert/DoubleOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/convert/IntOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/convert/StringOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/number/DivideOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/number/MultiplyOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/number/SubtractOperationTest.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/operation/builtin/number/SumOperationTest.kt
Related to https://github.com/ZupIT/beagle/issues/1823
=> feat: Adds type coertion + unit test

beagle/src/main/kotlin/br/com/zup/beagle/android/context/GlobalContext.kt
=> fix: Fixes GlobalContext.set

beagle/src/main/kotlin/br/com/zup/beagle/android/context/GlobalContext.kt, beagle/src/test/kotlin/br/com/zup/beagle/android/context/ContextDataManagerTest.kt
Signed-off-by: Hernand Azevedo <hernand.azevedo@zup.com.br>
=> fix: Fixes GlobalContext.set with param BeagleConfig
